version: '3.5'

services:
    postgres:
        container_name: postgres
        image: 'postgres:alpine'
        ports:
            - '5432:5432'
        volumes:
            - 'postgresql_data:/var/lib/postgresql'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - app-net

    rabbitmq:
        image: 'rabbitmq:3-management-alpine'
        container_name: rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
            - 'rabbitmq_data:/var/lib/rabbitmq'
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
        networks:
            - app-net

    api:
        build: ./api
        command: yarn dev
        container_name: pass_api
        ports:
            - '4000:4000'
        environment:
            - DATABASE_URL=postgres://postgres:postgres@localhost:5432/pass_api
            - JWT_SECRET=bro_this_is_a_insane_secret
        volumes:
            - ./api:/usr/app
        depends_on:
            - postgres

    engine:
        build: ./engine
        command: cargo watch -x run
        container_name: pass_engine
        environment:
            - DATABASE_URL=postgres://postgres:postgres@localhost:5432/pass_engine
        volumes:
            - ./engine:/usr/app
        depends_on:
            - postgres

networks:
    app-net:
        driver: bridge

volumes:
    postgresql_data:
        driver: local
    rabbitmq_data:
        driver: local
